######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 12 12:50:50 2010
######################################################################

TEMPLATE = app
TARGET = hotd
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += hod.h hodhelp.h hodset.h
SOURCES += hod.cpp hodhelp.cpp hodset.cpp main.cpp
RESOURCES += hod.qrc

win32 {
RC_FILE     = icon.rc
}
